server:
  port: 8099
spring:
  application:
    name: "AuthService"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  security:
    jwt:
      secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 60000 # 1 dakika
      refresh-expiration: 120000 # 7 gün


  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:stage_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "authservice"
    description: "Green Project AuthService"
    version: "1.0.0"

logging:
  level:
    org:
      springframework:
        security: DEBUG




app:
  google:
    client-id: 990624623867-o83douun4e0vke2nur5qteo9pr4mmlf8.apps.googleusercontent.com
  cookie:




