server:
  port: 8099
spring:
  application:
    name: "AuthService"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 990624623867-o83douun4e0vke2nur5qteo9pr4mmlf8.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email , profile , openid



    jwt:
      secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 60000 # 1 dakika
      refresh-expiration: 120000 # 7 gün
      # 7 gün

  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://45.147.47.129:3306/algorycodedb
    username: algorycode
    password: algorycode1.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "authservice"
    description: "Green Project AuthService"
    version: "1.0.0"

logging:
  level:
    org:
      springframework:
        security: DEBUG


app:
  cookie:
    domain: localhost
    secure: false




